### ISSUE TITLE
Failed to upload lastest binaries

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/appdirs-feedstock#13]
The latest merge commit has failed to upload the binaries, despite being retried: https://github.com/conda-forge/appdirs-feedstock/runs/1274842094

I'm not sure if it's related but the bot also failed to re-render the PR before this merge was done: https://github.com/conda-forge/appdirs-feedstock/pull/11#issuecomment-711528606

@conda-forge/core Can someone take a look?

**Comment by ocefpaf** [comment]
Just tried to restart, with a re-render, again. Fingers crossed.

**Comment by beckermr** [comment]
If you look at the output logs, you can see it is trying to push directly to the conda-forge channels. This won't work. Anytime you see this, it needs a rerender.

**Comment by chrisburr** [comment]
Ah I had rerendered in #12 but I hadn't rebased to pick up the changes to `conda-forge.yml`:

### #11 

https://github.com/conda-forge/appdirs-feedstock/blob/45f926e8780f18da9e51d04f3ad99db645aeb0f0/conda-forge.yml#L1-L6

### `master`

https://github.com/conda-forge/appdirs-feedstock/blob/fb38b2173365ee74dbd081c40028a600890eacd9/conda-forge.yml#L1

Thanks for the quick help! It's worked now.
