### ISSUE TITLE
Delete arch versions from anaconda.org?

### ISSUE THREAD

**Issue by sdvillal** [conda-forge/appdirs-feedstock#7]
Right now we have arch and noarch versions of this on the conda-forge channel. This leads to an ugly warning from the resolver:

```
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::appdirs-1.4.3-py_0.tar.bz2
  - conda-forge::appdirs-1.4.3-py27_0.tar.bz2
```

Should we do nothing, delete the arch versions from the channel or simply bump the build number of the noarch version?

**Comment by ocefpaf** [comment]
Bumping the build number is OK.
Done in #8
